### ISSUE TITLE
revs745-746, Toolset Shutdown during Treebuilding

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#271] opened 2016-03-25 18:10 UTC
This happened to me yesterday, but I was hoping it was a fluke. It's now happened again, though. 

There's no warning -- and consequently no debug output or error message -- the toolset just spontaneously closes. Not sure what other information I can give you, @KFreon .

I wasn't doing anything else super-intensive on my PC, short of a little web browsing...4 tabs open in firefox... and I did have the Plot Database open. But, that's it. I do keep a CPU/RAM/Swap widget on my desktop, but it was obscured by my browser during the moment of the crash.

**Comment by KFreon** [comment] 2016-03-25 21:12
EventViewer might be able to give some more information. 
Hopefully it'll be able to specify which bit crashed.

**Comment by ghost** [comment] 2016-03-25 21:35
@KFreon -- Ah, that was very helpful; I should have thought of it. Here's what we have:

![texcrash_eventviewer](https://cloud.githubusercontent.com/assets/13645804/14054471/cdd26354-f296-11e5-8b03-c3cef89139d8.PNG)

**Comment by KFreon** [comment] 2016-03-26 07:20
Oh dear.
This error is a catastrophic failure of something in .NET, likely during Garbage Collection apparently.
There should be a minidump file somewhere that would help, but I don't know where it'd be.

**Comment by ghost** [comment] 2016-03-26 14:41
@SirCxyrtyx -- Happen to know where I'd find this minidump, lol?

@KFreon -- The fact that this is all of a sudden happening again makes me nervous. Texplorer used to do this on me quite frequently a while back, especially during ME1 treebuilding (which takes twice as long as the other two games). Treebuilding has been rock solid for me since around rev700-720, so seeing this happening again makes me wonder what changes have been made since that are making treebuilding less stable again. It's not fun to wait for 20 minutes and then have Texplorer shut down without warning when you're in the home stretch. It's actually part of the reason I stopped trying to perma-mod ME1. Has anything recently been changed at a real fundamental level? Things like memory/core usage, etc.

**Comment by KFreon** [comment] 2016-03-26 21:38
This is related to #280 and the reason for the sudden crash.
I need to try and figure out where this could be happening, and why.

**Comment by ghost** [comment] 2016-03-26 22:20
I figured it probably was, but it was the first time I actually got an error window, so I treated it differently, just in case. Let me know if there's any potential solutions you want me to test, @KFreon. As in, prior to a new rev :)

**Comment by KFreon** [comment] 2016-03-26 22:23
The only testable solution before a rev is to run it through VS :)

**Comment by ghost** [comment] 2016-03-26 23:08
Oh balls. I tried that once and it wasn't pretty. My computer freaked the fuck out on me when I tried to install it.

Are you able to replicate the issue, @Kfreon?

**Comment by KFreon** [comment] 2016-03-26 23:18
I've never had VS die on me like that no.
Maybe it's that old Windows 7 you're running... :P

**Comment by ghost** [comment] 2016-03-26 23:39
@KFreon -- LOLOL. I'd actually really like to update to Windows 10, but...

Has Microsoft removed all that telemetry spyware yet?

Yeah.... I thought not.

**Comment by KFreon** [comment] 2016-03-26 23:50
It was probably there in Win7 too, but no one noticed :P 
Anyway, I had VS on Win7 too and never had it die there either.

**Comment by ghost** [comment] 2016-03-26 23:57
@Kfreon -- FYI, I meant can you replicate the toolset crash and error?

**Comment by KFreon** [comment] 2016-03-27 00:03
Ohhh.
No I can't. Were you doing anything weird like scanning a million times without closing the toolset, or installing a million textures?

**Comment by KFreon** [comment] 2016-03-27 00:13
Actually, was this with ME1 scanning? I did manage to get it during ME1 scanning.

**Comment by ghost** [comment] 2016-03-27 00:13
@Kfreon -- Well, maybe scanning ME3, ME2, ME1. Not a million times. Not any installation at all.

And, for when I actually got the error message in the other issue, I simply had Texplorer open and then opened a texture in Image Engine. No scanning and no installing at all.

**Comment by KFreon** [comment] 2016-03-27 00:40
Ah that's a different error then. 
I haven't been able to reproduce such an error.

Is that texture you open in image engine repeatable?

**Comment by ghost** [comment] 2016-03-27 01:07
@KFreon -- Doesn't seem like it. I just opened it again with Texplorer open in the background and it's not throwing the error.

It does seem like it actually is a result of the same thing, though. Like I said initially, in Event Viewer there was a similar NET framework error as what I dug up yesterday.

**Comment by KFreon** [comment] 2016-03-27 01:24
Yeah it's an ImageEngine bug related to how I deal with images.
Somehow a pointer is getting out, but I can't see how...
I've added some catch logic in to hopefully help find this.

**Comment by ghost** [comment] 2016-03-27 01:26
@KFreon -- Okay, sounds good. Hopefully it happens again as I continue to test.

**Comment by ghost** [comment] 2016-03-28 17:22
@KFreon -- No errors yet.

One thing I did do was run Windows Updates. I hadn't in a couple months and there was actually a NET Framework update -- 4.6.1 or something. So, hopefully we're lucky and that's all it was. 

I just built a ME3 tree with other tools and other external programs open without problems. It was only crashing about 25-33% of the time though, so, I'll need to rebuild again a few more times to get a better idea.

**Comment by KFreon** [comment] 2016-03-29 02:10
That .net update sounds like a winner. I can't remember if the toolset uses it or not anymore, but either way. :)

**Comment by Mgamerz** [comment] 2016-03-30 20:02
.net 4.6 had some tail end recursion bugs that were fixed in 4.6.1. It would essentially skip instructions if you had a 1 parameter method call in some instances.

**Comment by ghost** [comment] 2016-03-31 17:39
No crashes during treebuilding on rev 747, and after I did the NET update, @KFreon.

It's still possible that I haven't re-built trees enough to replicate the problem, but if you want to close the issue I'd say it's relatively safe to do so. If I experience it again, I can reopen.

**Comment by KFreon** [comment] 2016-03-31 22:27
Sounds good.
Does that mean I can close #280 as well?

**Closed as completed by KFreon** 2016-03-31 22:27 UTC
Labels: bug

**Comment by ghost** [comment] 2016-04-07 18:52
@KFreon -- I'm going to say this is verified in rev748. Built 4 trees and no crashes. Maybe it was indeed just the NET update.
