### ISSUE TITLE
TPF/DDS Tool running out of memory

### ISSUE THREAD

**Issue by Rodumas** [ME3Explorer/ME3Explorer#441] opened 2016-10-19 19:52 UTC
http://pastebin.com/DamVuCvU

Ran into some problems while installing ALOT for ME2. Some textures were skipped due to a System.OutOfMemoryException. Where a folder that contained 220 texturefiles only successfully installed 191, weeding out said problem files resulted in most of the 'skipped' files successfully installing on a one by one basis. Some went through immediately, some had to be autofixed. All but one let themselves get installed in the end

Yes, I ran ME3explorer as admin.
Yes, I was modding the correct path to ME2.

And I was using 2.0. I know there is a 3.0 but I havent had time to look at it yet.

Above is a copy of the debug log. I was told to just post this here so I am.

**Comment by KFreon** [comment] 2016-10-19 21:28
Pretty much any answer you can get here is "try version 3".
It's much improved. If you still have issues like this with V3 we definitely need to know about that.

With V2 you can try closing everything you can and maybe limiting the number of threads in the options menus.

**Comment by SlaterEvolution** [comment] 2016-10-21 06:03
I'm having the same issue except I am using version 3. I'm using it to mod ME2 with textures just like Rodumas using the TPF/DDS tool and unfortunately a select few files will just never go through no matter how many times i run it because of a "system.outofmemory" error despite the fact I have 16GB of ram available.  

I've attached the log for just one of the few files that are causing this issue. The reason why only one is just to eliminate the possible factor of me trying to install too many textures at once. But as you can see even just trying to install this single specific texture file it just won't go through.

[log.txt](https://github.com/ME3Explorer/ME3Explorer/files/543613/log.txt)

I am curious though, is there some hard coded memory limit in ME3Explorer? I've never seen the program itself go over 2GB despite my system having plenty of RAM. While processing the file in that log, it did spike up to 1.9GB during processing once. Also after analysing it the memory usage on ME3Explorer went from ~100MB to ~700MB even after clearing all files from the TPF/DDS tool.

**Comment by KFreon** [comment] 2016-10-21 11:40
Regarding memory, I tried to keep the ram below 4gb as that's a common memory amount. Not so much now, and my new version will handle ram smarter when I get to it.

Now, I'm assuming that mod works for others?
Are you files vanilla?

**Comment by SlaterEvolution** [comment] 2016-10-21 13:03
Yes the mod works for others with no problem and files are vanilla. Verified it with Origin as well just in case.

**Comment by starkgate** [comment] 2016-10-21 13:47
Could ME3Explorer be limited to 2 GB of RAM used ? (32bit programs are limited in memory iirc, but I don't know if ME3Explorer is 32 or 64 bit).

There were issues with ME2 texture installation, a few versions ago. Is it possible that this is caused by a leftover of these issues ?

**Comment by KFreon** [comment] 2016-10-21 21:12
Hmm if it spiked up to ~2gb creeper might be right. It's somehow loading too much.
You could try lowering the threads for the tools.

**Comment by Rodumas** [comment] 2016-10-22 13:06
Yes I upgraded to version three ( relatively easy, I love that it seems....faster) Installed the game on a different drive and changed the paths accordingly. I installed alot , but when it came to this particular folder, it happened again. Now all the while I was doing this I wondered about something.Would it matter if the tool is installed on a different driver than the gamefiles?

**Comment by starkgate** [comment] 2016-10-22 15:31
It shouldn't, not if the cause is memory.

**Comment by SlaterEvolution** [comment] 2016-10-22 19:18
How would I go about lowering the number of threads for it?

**Comment by KFreon** [comment] 2016-10-22 20:28
There's an option in the toolset settings panel for it. I think I removed it on texplorer and tpftools. 

I'll test that mod in a few days when I get home.

**Comment by SlaterEvolution** [comment] 2016-10-23 05:41
Yeah last i checked there wasn't such an option but then again i haven't exactly been touching things I don't know too much about just yet.

**Comment by SirCxyrtyx** [comment] 2016-10-23 22:22
The thread option was removed in 3.0. I think the only place the setting was actually used was for loading TPFs into TPFTools.

**Comment by SlaterEvolution** [comment] 2016-10-24 05:05
Hopefully that option will allow us to get around this issue.

**Comment by KFreon** [comment] 2016-10-25 22:03
Do you have a link to the mod?

**Comment by starkgate** [comment] 2016-10-26 08:07
If it's ALOT for ME2 you're looking for, here you go : http://www.nexusmods.com/masseffect2/mods/68/?

**Comment by KFreon** [comment] 2016-10-26 10:50
Thanks Creeper, but @SlaterEvolution had a single texture that causes this issue.
I don't have good internet so I'd rather not run out of quota too fast :)

**Comment by SlaterEvolution** [comment] 2016-10-26 16:55
@KFreon It's not just that one texture out of the lot, it's actually a small handful that I've painstakingly weeded out through multiple runs. The log i posted was only of the one that for me personally has been the most annoying. I could load in all the troublesome ones at once but it would simply be a log of "out of memory errors".

**Comment by KFreon** [comment] 2016-10-26 22:12
Can you package some up for testing?

**Comment by SlaterEvolution** [comment] 2016-10-27 06:07
If you mean load up the troublesome ones together in a single batch to run then sure.
[log.txt](https://github.com/ME3Explorer/ME3Explorer/files/555053/log.txt)

Thing is with one of the textures, "MASSEFFECT2.EXE_0xF1EB9877" it splits into two "files" in TPF tools. They're called HMF_KEN_CTHa_Rou_Norm_Stack & HMF_KEN_CTHe_Rou_Norm_Stack. Both names are italicised in TPF/DDS tool after processing. 

One of the two actually goes through the "CTHa" one and the other fails and gives the memory error. But because they're both the same file I had to put that file under one of the ones causing memory errors.

**Comment by starkgate** [comment] 2016-10-27 06:36
Textures that "split" are duplicate files : an identical texture/hash is used twice by the game, with different names. ie they correspond to the same texture in ALOT.
Does the issue always happen with these italicized files ?

**Comment by SlaterEvolution** [comment] 2016-10-27 07:00
@CreeperLava With that specific file yes, there have been a few other cases where this happens but all the other cases, they all went through fine so it's just this specific file that has an issue somehow.

**Comment by KFreon** [comment] 2016-10-27 08:05
I meant zip them up and post them on Mega or something so I can test them.
The smaller the better :)

**Comment by SlaterEvolution** [comment] 2016-10-28 03:36
@KFreon Here you go, let me know when you're done downloading them. I'm only keeping them on there temporarily and want to remove them later on.

https://www.dropbox.com/s/4u69ztdejn7ejrn/ME2%20Textures.zip?dl=0

**Comment by KFreon** [comment] 2016-10-28 05:08
Got them, thanks.
I'll see what testing comes up with.

**Comment by SlaterEvolution** [comment] 2016-11-01 06:08
@KFreon Any updates on if you're getting the same errors Rodumas and I am?

**Comment by KFreon** [comment] 2016-11-01 06:38
Apologies, I'll do some testing now.

**Comment by SlaterEvolution** [comment] 2016-11-01 10:14
@KFreon No problem :) Just glad to know someone's looking into it!

**Comment by KFreon** [comment] 2016-11-03 03:01
I finally got around to testing, and immediately remembered why I don't like testing.
It breaks and I don't know why it's breaking, despite knowing precisely where.

Few questions:
1) That group of textures you sent, are they all supposed to break? the 32C and DAF ones go fine, then it dies at D09.
2) Has anyone else had issues installing 4k textures? It's crashing at a part where it's not my fault, it just thinks there's not enough RAM, so this should be a relatively common issue. 

The theory so far is that it's related to the 32 bit memory space getting too full to find a contiguous chunk of memory to fit a 4k texture.
If this is the case, it will be fixed when I rewrite the tools (since they'll be 64 bit) but that doesn't help now.

EDIT: I'm almost certain this is the case now. I'm able to install them separately, but not all in one go.

**Comment by SlaterEvolution** [comment] 2016-11-03 05:10
@KFreon The problem is that despite trying to install them one by one I still get system out of memory errors. The textures i sent aren't supposed to break, they're supposed to install just like any of the others. 

What i've noticed is that it's typically these ones specifically that I've seen their names pop up with problems in the mod's comments a couple of times. Not all of them for each user just some.

**Comment by KFreon** [comment] 2016-11-03 05:36
What I meant was do all of them cause an issue on your system?
How much RAM do you have?
Also have you tried closing down all non essential programs before running the toolset?

**Comment by SlaterEvolution** [comment] 2016-11-03 06:19
@KFreon Yes they all give the same memory error. I have 16GB of RAM and yes I have closed down all non essential programs in case for whatever reason that was the cause.

**Comment by KFreon** [comment] 2016-11-03 06:41
I am at a loss.
At the least, I can't think of a way to fix it in the Stable :(

**Comment by SlaterEvolution** [comment] 2016-11-03 10:44
@KFreon But it can potentially be fixed together with an update to Me3Explorer? I'm at a loss as well when it comes to this problem. 

I don't suppose you know what each of those textures i sent you are used for? I'm considering just playing through without them installed and just hope that they only affect uncommon objects/clothing so I won't notice.

**Comment by starkgate** [comment] 2016-11-03 11:31
You should be able to figure out what the textures are used for by searching for their hash in Texplorer. The name should give you some info, see here for a frequently used acronyms list : http://me3explorer.wikia.com/wiki/Textures_in_Mass_Effect

**Comment by KFreon** [comment] 2016-11-03 12:03
@SlaterEvolution It'll be fixed when I finish the rewrite of the texture tools.
I hope...

EDIT: And for now, I'll close this.

**Closed as completed** 2016-11-03 12:04 UTC
Labels: Kfreon

**Comment by GreatEmerald** [comment] 2016-11-06 09:27
I'm getting this too. Just to give more details for those searching about this problem:

This issue happens at two stages: loading textures and saving mods. When it happens during loading the textures, affected textures are shown as invalid with the indicators "FORMAT MIPS SIZE", with format being "Unknown", mips being "0" and size being "-1x-1". Trying to autofix those results in the tool freezing. Removing those textures from the list and readding them makes it work fine, but it's a bit of work to try and find out which files those textures correspond to. The errors related to this phase are:

```
Error checking texture: Insufficient memory to continue the execution of the program.
Error checking texture: MILERR_WIN32ERROR (Exception from HRESULT: 0x88980003)
```

When it happens during the save phase, the result is that the tool shows less mods installed than there should be (like 61/68). Trying to apply the textures again may or may not help. And figuring out which textures failed is much more difficult. In this phase, the errors look like:

```
Unknown error with mod:  HMF_ARM_CTHc_Sto_Norm_Stack, skipping.
(Error:  Exception of type 'System.OutOfMemoryException' was thrown.)
```

In all cases this happens randomly. Retrying will result in completely different textures failing to load/be written. This also affects ALOT minor releases, not just the major ones.

The memory usage never reaches anywhere near full, so my first thought was also that it is running out of virtual memory due to being 32-bit. Seems like that is corrrect. Doing anything in 32-bit these days doesn't make much sense to begin with... So I'm looking forward to the 64-bit release.

**Comment by KFreon** [comment] 2016-11-06 13:34
I'm starting to wonder if its less about the 32 bit memory space and more about how Windows handles the graphics subsystems. 
My hunch atm is it's something like the graphics get allocated, but not deallocated, more specifically, not deallocated in time.
It seems crazy but I feel like it's allocating too much graphics memory and not releasing it fast enough. Apparently this can be a thing, and the fix is to wait for finalizers to complete, and this seemed to have some, but limited, effectiveness. 
What really bothers me, is that when I remove the code that's breaking...it still breaks.

I don't understand how this is new. The fancy stuff Sir has done shouldn't affect Texplorer or TPFTools, and I haven't changed anything in those for ages.

Anyway, hopefully this just goes away with the rewrite, when I eventually get around to it...

**Comment by GreatEmerald** [comment] 2016-11-06 14:35
Graphics memory as in VRAM? Hm, I didn't try monitoring that. System RAM does indeed spike quite a bit, mind you. It looks like it does increase by 2 GiB or more while loading a large batch of textures. Overall the RAM usage goes in a bit of a sawtooth pattern, with a bit sharper falls than climbs.

Yes, I doubt it's new. I started using ME3Explorer at the 3.0.0 release, and the issue was there from the start. But it's the kind of issue that's not obvious, because the tool continues working seemingly fine. The issue becomes apparent only when you start looking into the finer details.

**Comment by KFreon** [comment] 2016-11-06 22:17
Not VRAM, but the unmanaged memory that the bitmaps live in. Yeah it does spike and dip a fair bit due to loading big images and PCCs to work on. 
This stuff has been in since before the 3.0 stable though, and Creeper has been installing thousands of textures.
Hell I was installing bunches of textures a while ago, and this never happened. But with that one set of images...Very strange.

EDIT: Forgot to thank you for the information :)
