### ISSUE TITLE
rev727 Version Switcher is broken

### ISSUE THREAD

**Issue by starkgate** [ME3Explorer/ME3Explorer#148] opened 2016-01-15 17:05 UTC
Whatever I try to do, I can't get it working. Logs are below, with description of the problem.

http://pastebin.ca/3333797

**Comment by Mgamerz** [comment] 2016-01-21 16:45
Make sure no files are open from within the folder. It is a windows limitation and partly because version switcher is part of the toolkit, which is being replaced (which is why it runs that command prompt window, so it can shutdown). Without being able to run C# to manage the swap there is no way to know what files are keeping the folder locked.

**Comment by starkgate** [comment] 2016-01-21 17:50
I don't think any file was open in the initial me3explorer folder. The problem doesn't seem to lie there, if you read the log closely.
In the first case (running me3explorer from root of C drive) :
'System.IO.IOException: Le fichier 'C:\Users\w42\AppData\Local\Temp\Debug\AmaroK86.ImageFormat.dll' existe déjà.'
Meaning the dll already exists and can't be overwritten (possibly). Which is odd because I definitely haven't opened any file in the Temp folder, and it was empty before...

In the second case (running me3explorer from D drive) :
System.IO.DirectoryNotFoundException: Impossible de trouver une partie du chemin d'accès 'C:\Users\w42\AppData\Local\Temp\ME3Explorer\VersionSwitcher.exe'.
Meaning it can't find a part of the file path to the exe. Maybe the double '/' are part of the problem ? Otherwise I don't know, I checked the location and the exe was there.

**Comment by Mgamerz** [comment] 2016-01-22 17:50
The issue is that KFreon uploaded (maybe in the past) the release packaged wrong. This has been happening since 722 off and on. This is not a problem with version switcher. The top level folder in the zip file must be named ME3Explorer, that is the only way it will work.

At least, that's what the first message seems to mean. The "Debug" folder should not be there. It could be leftover from old versions of ME3Explorer, and a new release tried to extract there again (packaged as Debug instead of ME3Explorer) and it was never deleted because the script isn't designed to delete anything in %temp% except a folder named ME3Explorer. When it extracts, that file would then exist since it was never previously deleted.

Deleting the "Debug" folder would solve the first issue, but the second issue would remain because the folder is not named correctly. This could be 727 only though, cause I DL'd 728 a day or so ago and it seemed to be OK.

**Comment by starkgate** [comment] 2016-01-22 21:34
Right, I'll try it again this WE with 729. I'm not sure it will help though. Can't you simply tell your script to remove the whole me3explorer instead of specifying the folders ? Btw, if there was a folder before (which is possible, now that I think of it), it would probably be because of a previous failure of Version Switcher which left over the remains of the downloaded and extracted me3explorer folder.

I'll test it out more and get back to you with details tomorrow hopefully :).

**Comment by starkgate** [comment] 2016-01-23 14:22
Well, it definitely didn't work with rev729. Version Switcher downloaded rev730, closed me3explorer and apparently stopped there. The initial 729 folder still only contains the 729 revision. I have a me3explorer.exe_some_random_numbers.iTrace file in my windows/temp folder, no idea what that is. I used the source version of me3explorer, but that shouldn't stop Switcher from working right ?
No log either.

**Comment by Mgamerz** [comment] 2016-01-28 18:11
Delete anything related to ME3Explorer from your temp directory. I just switched 730 => 729 and 729 => 730, no issues, though probably should have made the command prompt auto close instead of waiting for the .exe to finish running. Oh well.

Also it is important for version switcher to be very specific about what folder to delete... if something went wrong, your entire desktop, or worse could vanish (and no recycle bin!).

**Comment by starkgate** [comment] 2016-01-29 13:45
I followed your instructions : emptied the temp folder, I placed my me3explorer_r731 directory in a folder without special characters or spaces. I even closed the explorer window showing this directory. But still, Version Switcher didn't seem to work. I end up with an empty me3explorer_r731 directory and the 730 files in my temp folder. I don't know what is wrong, but there is clearly a problem somewhere.

Also, when VS is working correctly, does it keep trees and thumbnails when switching ? It doesn't look like it would, and I was wondering if you could make it work. It would be quite the surprise for beginners to see their trees deleted without backup.

**Comment by ghost** [comment] 2016-02-08 18:24
@CreeperLava -- Version Switcher worked fine, going from rev731 back to rev730. There are two changes that need to be made, but I'll submit those as separate issues, since they aren't tied to overall functionality as this issue is.

**Comment by ghost** [comment] 2016-02-11 14:23
Closing due to removal from toolset.

**Closed as completed by ghost** 2016-02-11 14:23 UTC
Labels: wont fix
