### ISSUE TITLE
Rev723 Failed to add high-resolution textures

### ISSUE THREAD

**Issue by Djencool** [ME3Explorer/ME3Explorer#112] opened 2015-12-05 17:02 UTC
This problem occurs if any "DXT1" or "DXT5", while trying to replace the texture into the texture tree, it's just an error when checking the file format replaces and standard, a file that is added is of type DDS_DXT "right type", and the standard just DXT "right type "details in the picture
![123](https://cloud.githubusercontent.com/assets/16167280/11609018/c9b919b8-9b9b-11e5-8f02-1969ffde4686.png)
![1234](https://cloud.githubusercontent.com/assets/16167280/11609019/c9d47ec4-9b9b-11e5-95bb-e0b9ea44af2e.png)
![123456](https://cloud.githubusercontent.com/assets/16167280/11609020/c9d7658a-9b9b-11e5-93b1-907214e40d60.png)

**Comment by starkgate** [comment] 2015-12-12 21:44
Probably related to #97 and #116, thanks for the detailed report ! Edit : also seems to be a duplicate of #111.

**Comment by starkgate** [comment] 2015-12-24 12:29
Works in 725. Also throws an error, but the image is still correctly replaced.
![capture](https://cloud.githubusercontent.com/assets/12874678/11994630/42fe0d9c-aa42-11e5-995d-f5aaefe96564.PNG)

**Comment by KFreon** [comment] 2015-12-29 21:49
How can that error even be thrown? 
HRHRHRHRHURURUUR. We really need to get your VS working.
This weird stuff is getting on my nerves. It might be that somehow the versions of the dependencies we use are wrong, but I have the latest so it doesn't happen to me.
This one though just shouldn't be able to get to the user.

**Comment by starkgate** [comment] 2015-12-30 09:21
Well, you'll tell that to my computer, maybe he'll understand if it comes from you^^.

**Comment by KFreon** [comment] 2015-12-30 22:22
If only it were so simple :P 
Alas. VS must be fixed!

**Comment by starkgate** [comment] 2016-01-16 21:23
Just to confirm, "Add Bigger Image" works in rev728. There is only a slight problem, the preview image (the one obtained by double-clicking the texture), doesn't get updated with the newly installed texture. Extracting the said texture does get you the upscaled texture, so at least that confirms the success of the installation.

**Comment by KFreon** [comment] 2016-01-23 04:23
Fixed.

**Closed as completed** 2016-01-23 05:20 UTC
