### ISSUE TITLE
V3.0 Speed on AMD cpus

### ISSUE THREAD

**Issue by zanda268** [ME3Explorer/ME3Explorer#437] opened 2016-10-13 16:50 UTC
I never used any of the versions before 3.0 so I have no comparison, but it appears that using your tool takes much longer on amd cpus than it should. I have a decent [pc](http://pcpartpicker.com/user/zanda268/saved/#view=sDh6Mp) and nothing was ever even close to being maxed out. 
Unpacking dlc on a clean install takes well over an hour and using the TPF tool to install ALOT took at least 6 hours from start to finish. While ALOT is a huge file to process, most intel users reported times as low as 45 minutes while at least one other amd user noted a time worse than mine.

I am unsure is this is something that you guys can fix (possibly splitting up the task to use multiple cores) or if this is just something we will have to deal with. Regardless, thanks for the awesome tool.

**Comment by ghost** [comment] 2016-10-13 21:26
> Unpacking dlc on a clean install takes well over an hour

There's nothing  wrong with this. It's entirely dependent on how many DLC you have. Unpacking hs been known to take some folks 2-3 hours, though that was more common prior to v3.0.

> and using the TPF tool to install ALOT took at least 6 hours from start to finish. While ALOT is a huge file to process, most intel users reported times as low as 45 minutes while at least one other amd user noted a time worse than mine.

This also seems fine. Some ALOT users have reported 10 hour install times. It's a very large mod and every user's system is different. Creeper will be able to better tell you what time frame is appropriate.

> I am unsure is this is something that you guys can fix (possibly splitting up the task to use multiple cores) 
> The toolset already does this as far as I know, but Sir will be able to answer better than I.

@SirCxyrtyx  -- Leaving this open in case you have anything to add, but there's no issue here as far as I can tell.

**Comment by KFreon** [comment] 2016-10-13 22:12
The only way it could be related to the type of CPU is if the .NET framework had such a bias.
That is supremely unlikely considering it's well tested and widespread.

More likely possibilities:
1) AMD implementations not as efficient. Nothing we can do, just AMD being bad, but I don't think that's a thing these days. They're pretty equal now.
2) Something else in your PC is bottlenecking. Seems unlikely given that godly PC you've got there.

It does seem strange that that 8 core CPU isn't working faster than a 4 core, unless limited by disk.

**Comment by Tarshana** [comment] 2016-10-19 02:55
The issue is that AMD uses cores with shared components so every 2 cores share many of the parts making them more like 1.5 cores. You will have to prioritize this yourself in your windows task manager. Set everything to normal/low priority and ME3 explorer to high (do not forget to change back when you are done) and close out anything else. To be fair, my Beast machine is the one that took 45 minutes and that was shutting everything off; internet, all excess programs, etc. When I install textures I  make sure nothing else is going on and set the priority up. It is like min/maxing in video games.

**Comment by KFreon** [comment] 2016-10-19 05:17
So it's like hardware hyperthreading? Cool, didn't know that. 
I'm looking into how to improve performance of installing textures and stuff in my fork of the toolset. Hopefully I'll be able to use the gpu for some stuff.
Just fyi :)

**Comment by mirh** [comment] 2016-10-19 06:55
CMT is not the same of SMT (which intel's hyperthreading is). 
You have a fpu for every two integer cores. That in turn is "worth" either a single or dual core, depending on the kind of load. 
...
But aside of that, in 2016 I'd expect schedulers to be aware of that.

**Comment by Tarshana** [comment] 2016-10-19 07:38
CMT is what AMD tries to use as a marketing tool.. but it does not compare to SMT, not really.  Intel's SMT, or Simultaneous Multithreading, has been in development from IBM since the late 60's (me grand mum worked with early developers through IBM and Techtronix (not Xerox whoops) which is why I know this). AMD does not utilize its IPC the same way as Intel and to be frank, under performs against an Intel in the same class.  Most gamers (in my experience) use Intel because it is better at handling large loads and better graphics. That is not to say AMD is bad, just performs under what Intel does. An AMD 8 core is not the same as an Intel 8 core. I do not know if anything can be written to make it perform better, as I have been under the impression the AMD user has to configure their cores manually. I could be wrong as I have not used an AMD in over 10 years.

**Comment by mirh** [comment] 2016-10-19 10:24
I never pretended IPC to be comparable, I was just pointing out it's indeed different from whatever Intel does. 

Said this, I wouldn't know if ME3explorer is being cpu-limited or not. 
I'd still expect **at least** an 8350 to beat an i3, if the load was truly multi-threaded. 
Anybody has some point of reference?

**Comment by Tarshana** [comment] 2016-10-19 17:33
You mean like a compare chart? http://cpuboss.com/cpus/Intel-Core-i3-4340-vs-AMD-FX-8350

**Comment by mirh** [comment] 2016-10-19 18:32
Just some idea of the time taken by other CPUs, in ME3Explorer, provided of course you aren't hdd limited or something. 

And to be honest I don't think there exists a more crappy and superficial website than cpuboss.

**Comment by Tarshana** [comment] 2016-10-19 19:52
Ha, yeah. There is not much "testing" by unbiased parties. My laptop has an i7 and Beast has an i7 as does my Beast Jr so I have not way to compare with an i3.

**Comment by mirh** [comment] 2016-10-19 20:02
What? Pretty much every website is fine-ish as for benchmarks. The only dumb one is that. 

Besides, I guess even a laptop i7 is fine as a general reference. 
Of course if you could comment core usage it would be better.

**Comment by mirh** [comment] 2016-10-19 20:03
Now that I think, we all jumped over the "cpu-must-be-at-fault" bandwagon..

But did anybody ever ruled out other causes first of all?

**Comment by Tarshana** [comment] 2016-10-19 20:30
I apologize, I do not know much code so I can be of no more use to the discussion. I hope I brought extra information to the table surrounding how CPUs between the two chip makers work to help look into a key part of how the program runs :) I do hope that a solution can be found! 

Edit: Sorry if you  have answered this but are you on Win 10 by chance?

**Comment by KFreon** [comment] 2016-10-19 21:23
Although this cpu talk is interesting, it's also irrelevant when it comes to. NET and C#. It's too high level for us to have any control over what type of cpu we use and how.
That's all abstracted away by the geniuses at Microsoft.

It seems to me to be more likely a hardware limitation in some fashion, likely disk with that kind of speed increase.
Watching the performance or resources monitor should provide some insight.

**Comment by ghost** [comment] 2016-10-29 15:00
@KFreon, @SirCxyrtyx -- Can this be closed? This doesn't seem a new issue to v3.0 or to TPF Tools.

**Comment by zanda268** [comment] 2016-10-29 23:11
I'll go ahead and close it (forgive me if I shouldn't have) but I wanted to add one final note about limits other than cpu. I ran it first on a 5400 rpm hdd and then on an ssd with no performance change. Nothing else in my system should have bottlenecked except that.

**Comment by mirh** [comment] 2016-10-30 09:05
Meaning.. you moved the whole game and dlc to ssd or just me3explorer?

**Comment by ghost** [comment] 2016-10-30 16:46
@zanda268 -- I'm actually surprised users can close their own issues; we should probably take a look at that on our end. 

I'm re-opening just so K and Sir can take a final look. If it's closed, then it will likely drop off their radar.

**Comment by KFreon** [comment] 2016-10-30 22:24
Users can close their own so that if they realise they made a mistake, we don't have to do anything.

I feel like this topic can be closed for now since there's pretty much no evidence that the slowdown is related to the AMD CPU (no offence). I mean if there was some kind of slowdown due to AMD CPU's, who'd buy them?
Either way, we wouldn't be able to do anything anyway since the .NET Framework handles things itself.
EDIT: @SirCxyrtyx to check before closing in case I'm wrong :)

**Comment by zanda268** [comment] 2016-10-30 23:29
@mirh I moved everything. Nothing was on anything but my ssd.

**Comment by mirh** [comment] 2016-10-31 12:47
Mhh, so.. It looks suspicious then...
How's core usage during the operation?

**Comment by zanda268** [comment] 2016-10-31 20:41
I had Task manager up and nothing was close to being maxed out. I believe the cpu usage was sitting around 20-30% or so.

That's what makes me think your program is only running on one thread and therefore only using one of my cores.

**Comment by KFreon** [comment] 2016-10-31 22:01
Task Manager should show all cores so you could see if that was the case.
Texplorer and TPFTools should both use multi threads.

**Closed as completed** 2016-11-16 02:27 UTC
Labels: question, stable
