### ISSUE TITLE
V722 DTX1 dds not properly detected

### ISSUE THREAD

**Issue by Kinkojiro** [ME3Explorer/ME3Explorer#111] opened 2015-11-23 11:10 UTC
I am trying to replace a GUI image (no mipmaps, pcc held), with a similar image.  When replacing texplorer states:

Mission Failure:
Invalid Format. Selected image is DDS_DXT1. Required: DXT1.

The image is correct - even if I use DXT1 images that I have replaced in prior versions it doesn't like it.  Furthermore the DXT1 image doesn't matter where it is created (MS DX Texture Tool, GIMP or Paint.net all fail).

This didn't happen with 718 or earlier.

A sample of the problem file can be downloaded here:  https://dl.dropboxusercontent.com/u/64867763/MapMod/DXT1Problem.rar

Trident.dds is one example image with this problem (I haven't got any that work).

If you create a tree you can see that it is already in the pcc file (object VEH_MM_Trident) which was done before I moved to 722, so there is no reason it shouldn't work now.

**Comment by KFreon** [comment] 2015-11-25 07:16
You got a hash or something for that? 
Is it in the basegame or a DLC?

**Comment by starkgate** [comment] 2015-12-12 21:46
Probably related to #97 and #116, also seems to be a duplicate of #112.

**Comment by starkgate** [comment] 2015-12-24 12:30
I can't test it without a hash, but this is probably fixed as #112 is basically the same bug.

**Comment by KFreon** [comment] 2015-12-24 22:38
Yeah imma close this one.
112 will remain open for now since there's still weirdness going on.

**Closed as completed by KFreon** 2015-12-24 22:38 UTC
