### ISSUE TITLE
r733, Texplorer GUI problem

### ISSUE THREAD

**Issue by ghost** [ME3Explorer/ME3Explorer#171] opened 2016-02-12 23:14 UTC
Lol, sorry, @KFreon...:

![texplorerguiprob](https://cloud.githubusercontent.com/assets/13645804/13023168/1acdbdc4-d19b-11e5-9021-ac20ba8e3b34.PNG)

Can't select the game right now since it's not in the window.

Problematic, this is, my young padawan. 

Good thing mine is currently defaulted to ME3... I should still be able to get the other Texplorer testing done that I need to, lol.

**Comment by KFreon** [comment] 2016-02-13 10:15
Ugh this is tedious.
Does resizing help?

**Comment by ghost** [comment] 2016-02-13 15:36
@KFreon -- Nope. Sorry :/

**Comment by starkgate** [comment] 2016-02-16 09:56
All the GUI seems to be fixed in 735, at least for me^^.

**Comment by ghost** [comment] 2016-02-16 16:17
Ha. Not for me. 

For me it's identical to my screenshot above.

What's your monitor resolution?

**Comment by starkgate** [comment] 2016-02-16 16:22
3840x1080 (2 monitors merged by my graphics card). The problems I had before were because I resized the display, do you use your monitor's native resolution ?

**Comment by ghost** [comment] 2016-02-16 16:36
@CreeperLava -- Yes, native resolution. 1920x1080.

So, there's still scaling issues that means. The tools still aren't properly scaling for different resolutions. Every user is going to see something different based on their resolution. We 3 have different resolutions, and we all see something different. Someone with 1680x1050 will have different results from myself and both of you.

Problematic. See my other post in #149 . We need to start approaching this in a different way, I think.

**Comment by KFreon** [comment] 2016-02-20 05:51
Ok, fixed it on the other PC and it seems to work on the other PC.
Broken as hell on my 4k, but most people don't have one.

The cause seems to be the DPI and not the resolution anyway. I'll post more details on the release post. 
I'm also going to close all of these and if there're still problems, we can open a single thread for them.

**Closed as completed** 2016-02-20 06:00 UTC
Labels: bug

**Comment by ghost** [comment] 2016-02-22 15:28
Verified fixed in r738

**Comment by KFreon** [comment] 2016-02-25 21:49
Yaaaay! :D
