### ISSUE TITLE
TFP/DDS Tools: Not Found In Tree (rev748)

### ISSUE THREAD

**Issue by wild0077** [ME3Explorer/ME3Explorer#310] opened 2016-04-12 00:03 UTC
Hello everyone, I am currently using the rev mentioned on Title, which is 748, but just stumbled upon an issue while trying to install ALOT for ME2. I had successfully installed and tested, one at a time, Shepard.metpf, Characters.metpf and Environment.metpf, now I have only Squad.metpf to go. However, after I load this last one and hit Analyse, it instantly shows 0 valid images of 135, and that it wasn't found in tree. This is very strange cuz everything was going so smooth... I've been executing ME3Explorer as Admin, like always.

On the Debug window, the error repeats itself through out all files, so I just added a screenshot instead of log. Also added screenshot of program itself.

Would apreciate some help on this.

![2](https://cloud.githubusercontent.com/assets/18409056/14446084/8162cf00-0028-11e6-970d-f868b04063ac.JPG)

![1](https://cloud.githubusercontent.com/assets/18409056/14446052/4bc01d58-0028-11e6-9b1a-7a21341eb604.JPG)

**Comment by KFreon** [comment] 2016-04-12 01:17
Hrm...It couldn't find the hash for some reason.
Can you screenshot the texmod.log; Select last entry (something.log) and a bunch of text will replace the image preview. Just want to see the text.

**Comment by wild0077** [comment] 2016-04-12 01:22
I am sorry, I am new at this, how can I find this log?

**Comment by KFreon** [comment] 2016-04-12 03:16
Sorry I wasn't clear there. 
In tpftools, the last entry in the list is a file that details information about the tpf.
So if you load the tpf and scroll to the bottom, you'll see a thing called 'something'.log, probably texmod.log. 
Click that and the texture preview in the bottom right will change to text like:
0x537489|filename.dds
Etc

So if you can screenshot the toolset with that text displayed, that'd be great.

**Comment by matsmith83** [comment] 2016-04-12 16:06
I'm having the same issue, so I went ahead and took the screenshot...

![image](https://cloud.githubusercontent.com/assets/16199364/14466749/209cdba4-00d0-11e6-8233-7d62e27a0d02.png)

The rest of the text...

0x1B24F8A6|_0x1B24F8A6.dds
0x24C87859|_0x24C87859.dds
0x03C344C9|_0x03C344C9.dds
0x14377B74|_0x14377B74.dds
0xFC1CC3A9|_0xFC1CC3A9.dds
0xA2CA5292|_0xA2CA5292.dds
0x6073BE4B|_0x6073BE4B.dds
0x73041BF7|_0x73041BF7.dds
0x40197218|_0x40197218.dds
0x27539E1B|_0x27539E1B.dds
0x412E8CC3|_0x412E8CC3.dds
0x513B11FB|_0x513B11FB.dds
0x8A1A3EFB|_0x8A1A3EFB.dds
0x42EE7CBF|_0x42EE7CBF.dds
0xEB489979|_0xEB489979.dds
0x0C65B6C1|_0x0C65B6C1.dds
0xAAD59BE5|_0xAAD59BE5.dds
0x2C870E9C|_0x2C870E9C.dds
0xA604AB9B|_0xA604AB9B.dds
0x494583C5|_0x494583C5.dds
0xF7CFEEDF|_0xF7CFEEDF.dds
0x77477E37|_0x77477E37.dds
0xD30672BD|_0xD30672BD.dds
0xCC13CAB0|_0xCC13CAB0.dds
0x7054432F|_0x7054432F.dds
0x763D461C|_0x763D461C.dds
0xF21AE694|_0xF21AE694.dds
0x2B524A7F|_0x2B524A7F.dds
0x6F81ADB0|_0x6F81ADB0.dds
0x81B6386B|_0x81B6386B.dds
0xEB1A0D4F|_0xEB1A0D4F.dds
0x23D44C41|_0x23D44C41.dds
0x53E696B8|_0x53E696B8.dds
0xC312FF5A|_0xC312FF5A.dds
0x78BACD31|_0x78BACD31.dds
0x1B32B8AE|_0x1B32B8AE.dds
0x86B9C92C|_0x86B9C92C.dds
0x739A3FD4|_0x739A3FD4.dds
0x060947CB|_0x060947CB.dds
0x4AE24851|_0x4AE24851.dds
0xA2F2881F|_0xA2F2881F.dds
0xDAA5EF07|_0xDAA5EF07.dds
0xD28DE3C3|_0xD28DE3C3.dds
0x422AAA0D|_0x422AAA0D.dds
0x794E9EEB|_0x794E9EEB.dds
0xC05A6403|_0xC05A6403.dds
0x1D0EFF6A|_0x1D0EFF6A.dds
0x66C0D06A|_0x66C0D06A.dds
0x5674B1E3|_0x5674B1E3.dds
0x3C14826C|_0x3C14826C.dds
0x6B8C8EDA|_0x6B8C8EDA.dds
0x59CE0EFA|_0x59CE0EFA.dds
0xF1E9E572|_0xF1E9E572.dds
0x6134F6C1|_0x6134F6C1.dds
0xB389BFE6|_0xB389BFE6.dds
0xA1083260|_0xA1083260.dds
0x295EF654|_0x295EF654.dds
0x1FACB1D2|_0x1FACB1D2.dds
0x5AD80E8D|_0x5AD80E8D.dds
0x88EB2BA1|_0x88EB2BA1.dds
0xD2A27A35|_0xD2A27A35.dds
0x144CBEA8|_0x144CBEA8.dds
0xC32392A8|_0xC32392A8.dds
0x0C00F4B9|_0x0C00F4B9.dds
0xF72319ED|_0xF72319ED.dds
0x0857FDDD|_0x0857FDDD.dds
0xF8F9B78A|_0xF8F9B78A.dds
0x78E6BFB3|_0x78E6BFB3.dds
0xC44AA6C0|_0xC44AA6C0.dds
0x2197F5A4|_0x2197F5A4.dds
0xCB6FC26E|_0xCB6FC26E.dds
0xE256975C|_0xE256975C.dds
0x9610A1DB|_0x9610A1DB.dds
0x8B93936A|_0x8B93936A.dds
0x27144797|_0x27144797.dds
0xADB25A17|_0xADB25A17.dds
0xBC96D4E7|_0xBC96D4E7.dds
0xDF6E34F8|_0xDF6E34F8.dds
0xA3338B6D|_0xA3338B6D.dds
0x3F7A2FDB|_0x3F7A2FDB.dds
0x188B9641|_0x188B9641.dds
0x9C26A3D4|_0x9C26A3D4.dds
0x3EB6518D|_0x3EB6518D.dds
0x74797C1D|_0x74797C1D.dds
0xCEFCAAD5|_0xCEFCAAD5.dds
0x0898E4C4|_0x0898E4C4.dds
0xD2594770|_0xD2594770.dds
0x2AB9EE11|_0x2AB9EE11.dds
0xFB97ADA4|_0xFB97ADA4.dds
0x8E0FED2B|_0x8E0FED2B.dds
0xB0955232|_0xB0955232.dds
0x6C0B66E9|_0x6C0B66E9.dds
0xCFBA92C3|_0xCFBA92C3.dds
0xF1EC37D3|_0xF1EC37D3.dds
0xAE4CB759|_0xAE4CB759.dds
0xECA7DA8F|_0xECA7DA8F.dds
0x2EFA7C4A|_0x2EFA7C4A.dds
0x822EEFB1|_0x822EEFB1.dds
0x4C42CC1B|_0x4C42CC1B.dds
0xB0AD677B|_0xB0AD677B.dds
0xBE6438F1|_0xBE6438F1.dds
0x3AF35864|_0x3AF35864.dds
0xD1A5907F|_0xD1A5907F.dds
0x12BC8488|_0x12BC8488.dds
0xA1ED7C19|_0xA1ED7C19.dds
0xF9EDDE8C|_0xF9EDDE8C.dds
0x4A6EF885|_0x4A6EF885.dds
0xC4352C8B|_0xC4352C8B.dds
0x6B4E665A|_0x6B4E665A.dds
0xDF616B7E|_0xDF616B7E.dds
0x1F1248ED|_0x1F1248ED.dds
0xA8A24FB2|_0xA8A24FB2.dds
0x9A987362|_0x9A987362.dds
0x42DE22DF|_0x42DE22DF.dds
0x97644BC1|_0x97644BC1.dds
0x6FAF6D31|_0x6FAF6D31.dds
0x9A1EB56F|_0x9A1EB56F.dds
0xD9F76B49|_0xD9F76B49.dds
0xCE6A8AFC|_0xCE6A8AFC.dds
0x00D4CB41|_0x00D4CB41.dds
0xE5224E76|_0xE5224E76.dds
0xDC9A3469|_0xDC9A3469.dds
0x638AAD1C|_0x638AAD1C.dds
0xA51BFB2D|_0xA51BFB2D.dds
0x6E3C2E30|_0x6E3C2E30.dds
0x6CD2B8F2|_0x6CD2B8F2.dds
0x9E470305|_0x9E470305.dds
0x2FD222DE|_0x2FD222DE.dds
0xD138A0BF|_0xD138A0BF.dds
0x09C8641C|_0x09C8641C.dds
0x159BCAAE|_0x159BCAAE.dds
0x84FE3A29|_0x84FE3A29.dds
0x66453D73|_0x66453D73.dds
0x8F911553|_0x8F911553.dds
0x5DA8ECFF|_0x5DA8ECFF.dds

**Comment by wild0077** [comment] 2016-04-12 16:18
Don't know if still necessary, but I'm attaching mine as well xD

![3](https://cloud.githubusercontent.com/assets/18409056/14467243/bfa9ad1e-00b0-11e6-9d91-e1c49fe9413a.JPG)

> Full Text

 0x1B24F8A6|_0x1B24F8A6.dds
0x24C87859|_0x24C87859.dds
0x03C344C9|_0x03C344C9.dds
0x14377B74|_0x14377B74.dds
0xFC1CC3A9|_0xFC1CC3A9.dds
0xA2CA5292|_0xA2CA5292.dds
0x6073BE4B|_0x6073BE4B.dds
0x73041BF7|_0x73041BF7.dds
0x40197218|_0x40197218.dds
0x27539E1B|_0x27539E1B.dds
0x412E8CC3|_0x412E8CC3.dds
0x513B11FB|_0x513B11FB.dds
0x8A1A3EFB|_0x8A1A3EFB.dds
0x42EE7CBF|_0x42EE7CBF.dds
0xEB489979|_0xEB489979.dds
0x0C65B6C1|_0x0C65B6C1.dds
0xAAD59BE5|_0xAAD59BE5.dds
0x2C870E9C|_0x2C870E9C.dds
0xA604AB9B|_0xA604AB9B.dds
0x494583C5|_0x494583C5.dds
0xF7CFEEDF|_0xF7CFEEDF.dds
0x77477E37|_0x77477E37.dds
0xD30672BD|_0xD30672BD.dds
0xCC13CAB0|_0xCC13CAB0.dds
0x7054432F|_0x7054432F.dds
0x763D461C|_0x763D461C.dds
0xF21AE694|_0xF21AE694.dds
0x2B524A7F|_0x2B524A7F.dds
0x6F81ADB0|_0x6F81ADB0.dds
0x81B6386B|_0x81B6386B.dds
0xEB1A0D4F|_0xEB1A0D4F.dds
0x23D44C41|_0x23D44C41.dds
0x53E696B8|_0x53E696B8.dds
0xC312FF5A|_0xC312FF5A.dds
0x78BACD31|_0x78BACD31.dds
0x1B32B8AE|_0x1B32B8AE.dds
0x86B9C92C|_0x86B9C92C.dds
0x739A3FD4|_0x739A3FD4.dds
0x060947CB|_0x060947CB.dds
0x4AE24851|_0x4AE24851.dds
0xA2F2881F|_0xA2F2881F.dds
0xDAA5EF07|_0xDAA5EF07.dds
0xD28DE3C3|_0xD28DE3C3.dds
0x422AAA0D|_0x422AAA0D.dds
0x794E9EEB|_0x794E9EEB.dds
0xC05A6403|_0xC05A6403.dds
0x1D0EFF6A|_0x1D0EFF6A.dds
0x66C0D06A|_0x66C0D06A.dds
0x5674B1E3|_0x5674B1E3.dds
0x3C14826C|_0x3C14826C.dds
0x6B8C8EDA|_0x6B8C8EDA.dds
0x59CE0EFA|_0x59CE0EFA.dds
0xF1E9E572|_0xF1E9E572.dds
0x6134F6C1|_0x6134F6C1.dds
0xB389BFE6|_0xB389BFE6.dds
0xA1083260|_0xA1083260.dds
0x295EF654|_0x295EF654.dds
0x1FACB1D2|_0x1FACB1D2.dds
0x5AD80E8D|_0x5AD80E8D.dds
0x88EB2BA1|_0x88EB2BA1.dds
0xD2A27A35|_0xD2A27A35.dds
0x144CBEA8|_0x144CBEA8.dds
0xC32392A8|_0xC32392A8.dds
0x0C00F4B9|_0x0C00F4B9.dds
0xF72319ED|_0xF72319ED.dds
0x0857FDDD|_0x0857FDDD.dds
0xF8F9B78A|_0xF8F9B78A.dds
0x78E6BFB3|_0x78E6BFB3.dds
0xC44AA6C0|_0xC44AA6C0.dds
0x2197F5A4|_0x2197F5A4.dds
0xCB6FC26E|_0xCB6FC26E.dds
0xE256975C|_0xE256975C.dds
0x9610A1DB|_0x9610A1DB.dds
0x8B93936A|_0x8B93936A.dds
0x27144797|_0x27144797.dds
0xADB25A17|_0xADB25A17.dds
0xBC96D4E7|_0xBC96D4E7.dds
0xDF6E34F8|_0xDF6E34F8.dds
0xA3338B6D|_0xA3338B6D.dds
0x3F7A2FDB|_0x3F7A2FDB.dds
0x188B9641|_0x188B9641.dds
0x9C26A3D4|_0x9C26A3D4.dds
0x3EB6518D|_0x3EB6518D.dds
0x74797C1D|_0x74797C1D.dds
0xCEFCAAD5|_0xCEFCAAD5.dds
0x0898E4C4|_0x0898E4C4.dds
0xD2594770|_0xD2594770.dds
0x2AB9EE11|_0x2AB9EE11.dds
0xFB97ADA4|_0xFB97ADA4.dds
0x8E0FED2B|_0x8E0FED2B.dds
0xB0955232|_0xB0955232.dds
0x6C0B66E9|_0x6C0B66E9.dds
0xCFBA92C3|_0xCFBA92C3.dds
0xF1EC37D3|_0xF1EC37D3.dds
0xAE4CB759|_0xAE4CB759.dds
0xECA7DA8F|_0xECA7DA8F.dds
0x2EFA7C4A|_0x2EFA7C4A.dds
0x822EEFB1|_0x822EEFB1.dds
0x4C42CC1B|_0x4C42CC1B.dds
0xB0AD677B|_0xB0AD677B.dds
0xBE6438F1|_0xBE6438F1.dds
0x3AF35864|_0x3AF35864.dds
0xD1A5907F|_0xD1A5907F.dds
0x12BC8488|_0x12BC8488.dds
0xA1ED7C19|_0xA1ED7C19.dds
0xF9EDDE8C|_0xF9EDDE8C.dds
0x4A6EF885|_0x4A6EF885.dds
0xC4352C8B|_0xC4352C8B.dds
0x6B4E665A|_0x6B4E665A.dds
0xDF616B7E|_0xDF616B7E.dds
0x1F1248ED|_0x1F1248ED.dds
0xA8A24FB2|_0xA8A24FB2.dds
0x9A987362|_0x9A987362.dds
0x42DE22DF|_0x42DE22DF.dds
0x97644BC1|_0x97644BC1.dds
0x6FAF6D31|_0x6FAF6D31.dds
0x9A1EB56F|_0x9A1EB56F.dds
0xD9F76B49|_0xD9F76B49.dds
0xCE6A8AFC|_0xCE6A8AFC.dds
0x00D4CB41|_0x00D4CB41.dds
0xE5224E76|_0xE5224E76.dds
0xDC9A3469|_0xDC9A3469.dds
0x638AAD1C|_0x638AAD1C.dds
0xA51BFB2D|_0xA51BFB2D.dds
0x6E3C2E30|_0x6E3C2E30.dds
0x6CD2B8F2|_0x6CD2B8F2.dds
0x9E470305|_0x9E470305.dds
0x2FD222DE|_0x2FD222DE.dds
0xD138A0BF|_0xD138A0BF.dds
0x09C8641C|_0x09C8641C.dds
0x159BCAAE|_0x159BCAAE.dds
0x84FE3A29|_0x84FE3A29.dds
0x66453D73|_0x66453D73.dds
0x8F911553|_0x8F911553.dds
0x5DA8ECFF|_0x5DA8ECFF.dds

**Comment by ghost** [comment] 2016-04-12 17:06
Looks like this is what Creeper reported in #305, which I've now re-opened.

**Comment by alvarome** [comment] 2016-04-12 19:49
The texture file names are missing in that MEResults.log, I think... -?-

**Comment by alvarome** [comment] 2016-04-12 20:00
I just ran a quick test using rev748.

Loaded a -in this case- a ME2 .dds into TPF/DDS Tools.

Build TPF -> "no" (to be sure METPF is generated vs TPF) and... cleared the file.

Loaded the METPF and... no names at the MEResults.log. Only hashes as in those previous examples.

So I would say something is not rigth here, I´m afraid!

HTH!
Alvaro

**Comment by alvarome** [comment] 2016-04-12 20:02
Quick test using rev738 generates the MEResult.log as expected, including texture filenames.

If texture name is needed to trigger a flag in TPF/DDS tools that may explain why those are not recognized  in that ALOT METPF file -?-

HTH!
Alvaro

**Comment by starkgate** [comment] 2016-04-12 20:15
Apparently this issue has been fixed in the pre-release of rev749, so I will simply have to rebuild that METPF with it. Thanks for the information ! This issue can probably be closed.

**Comment by alvarome** [comment] 2016-04-12 20:18
No, wait, scratch my previous posts! Sorry! 

Yes, there is a bug indeed... but it is caused by a -from my understanding- wrong use of the tool.

Both rev 738 and 748 generates correct  and incorrect MEResult logs when building METPF files.

Just a matter of analysing the texture BEFORE generating the METPFS.

If analysed, everything is ok. But if you do not analyse the texture, then the METPF has no texture name, something that makes sense as the texture name is taken from the tree!

So a fix here would be to disable TPF/METPF creation BEFORE texture analysis. In other words, texture analysis shoud be mandatory to create METPFs.

HTH!
Alvaro

**Comment by starkgate** [comment] 2016-04-12 20:49
That is the bug indeed, and it has been fixed, see #305 :).

**Comment by ghost** [comment] 2016-04-14 14:06
Closing. This is a replicate of #305.

**Closed as completed by ghost** 2016-04-14 14:06 UTC
Labels: bug
